<?php
/**
 * Autogenerated by Thrift Compiler (0.8.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
include_once $GLOBALS['THRIFT_ROOT'].'/packages/hive_metastore/hive_metastore_types.php';

$GLOBALS['metastore_hive_metastore_CONSTANTS'] = array();

$GLOBALS['metastore_hive_metastore_CONSTANTS']['DDL_TIME'] = "transient_lastDdlTime";

$GLOBALS['metastore_hive_metastore_CONSTANTS']['IS_ARCHIVED'] = "is_archived";

$GLOBALS['metastore_hive_metastore_CONSTANTS']['ORIGINAL_LOCATION'] = "original_location";

$GLOBALS['metastore_hive_metastore_CONSTANTS']['META_TABLE_COLUMNS'] = "columns";

$GLOBALS['metastore_hive_metastore_CONSTANTS']['META_TABLE_COLUMN_TYPES'] = "columns.types";

$GLOBALS['metastore_hive_metastore_CONSTANTS']['BUCKET_FIELD_NAME'] = "bucket_field_name";

$GLOBALS['metastore_hive_metastore_CONSTANTS']['BUCKET_COUNT'] = "bucket_count";

$GLOBALS['metastore_hive_metastore_CONSTANTS']['FIELD_TO_DIMENSION'] = "field_to_dimension";

$GLOBALS['metastore_hive_metastore_CONSTANTS']['META_TABLE_NAME'] = "name";

$GLOBALS['metastore_hive_metastore_CONSTANTS']['META_TABLE_DB'] = "db";

$GLOBALS['metastore_hive_metastore_CONSTANTS']['META_TABLE_LOCATION'] = "location";

$GLOBALS['metastore_hive_metastore_CONSTANTS']['META_TABLE_SERDE'] = "serde";

$GLOBALS['metastore_hive_metastore_CONSTANTS']['META_TABLE_PARTITION_COLUMNS'] = "partition_columns";

$GLOBALS['metastore_hive_metastore_CONSTANTS']['FILE_INPUT_FORMAT'] = "file.inputformat";

$GLOBALS['metastore_hive_metastore_CONSTANTS']['FILE_OUTPUT_FORMAT'] = "file.outputformat";

$GLOBALS['metastore_hive_metastore_CONSTANTS']['META_TABLE_STORAGE'] = "storage_handler";

?>
